// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6t4FSmMY3yW5jA1H53n4fke0CJis1mM',
    appId: '1:882887991644:web:d67e1c127b3bd5ce0a6199',
    messagingSenderId: '882887991644',
    projectId: 'sorbonne-nouvelle',
    authDomain: 'sorbonne-nouvelle.firebaseapp.com',
    storageBucket: 'sorbonne-nouvelle.appspot.com',
    measurementId: 'G-XT1B582PWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATqSM08xD9nUs1HfWbdR3Jqg0LgJck85U',
    appId: '1:882887991644:android:02c494f3811b513b0a6199',
    messagingSenderId: '882887991644',
    projectId: 'sorbonne-nouvelle',
    storageBucket: 'sorbonne-nouvelle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9K4lucG8cgZCPrW7NCctCPIprQyWbglI',
    appId: '1:882887991644:ios:91994a2354f094930a6199',
    messagingSenderId: '882887991644',
    projectId: 'sorbonne-nouvelle',
    storageBucket: 'sorbonne-nouvelle.appspot.com',
    iosClientId: '882887991644-mc52v8tdqg1i7mkl2ethn44d4f7ucrn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flesn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9K4lucG8cgZCPrW7NCctCPIprQyWbglI',
    appId: '1:882887991644:ios:91994a2354f094930a6199',
    messagingSenderId: '882887991644',
    projectId: 'sorbonne-nouvelle',
    storageBucket: 'sorbonne-nouvelle.appspot.com',
    iosClientId: '882887991644-mc52v8tdqg1i7mkl2ethn44d4f7ucrn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flesn',
  );
}
